<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Buzz_oxd-buzz-post-input</name>
   <tag></tag>
   <elementGuidId>3e8becbe-f788-4e43-90d1-bb5b34ce456e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div/div/div/div/div/div[2]/form/div/textarea</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea.oxd-buzz-post-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>cc54807d-4665-4f7b-b5cb-11b81bf62d44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>de9df83c-c1f5-4cd5-b954-371394bdd743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oxd-buzz-post-input</value>
      <webElementGuid>06dac8ec-27a2-4c23-a2c0-465bef191e87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>What's on your mind?</value>
      <webElementGuid>3280e5b1-235d-4b4d-93c6-2997fdf74e66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout&quot;]/div[@class=&quot;oxd-layout-container&quot;]/div[@class=&quot;oxd-layout-context&quot;]/div[@class=&quot;oxd-grid-2 orangehrm-buzz-layout&quot;]/div[@class=&quot;oxd-grid-item oxd-grid-item--gutters&quot;]/div[@class=&quot;orangehrm-buzz-newsfeed&quot;]/div[@class=&quot;oxd-sheet oxd-sheet--rounded oxd-sheet--gutters oxd-sheet--white orangehrm-buzz-create-post&quot;]/div[@class=&quot;orangehrm-buzz-create-post-header&quot;]/div[@class=&quot;orangehrm-buzz-create-post-header-text&quot;]/form[@class=&quot;oxd-form&quot;]/div[@class=&quot;oxd-buzz-post oxd-buzz-post--focus&quot;]/textarea[@class=&quot;oxd-buzz-post-input&quot;]</value>
      <webElementGuid>a1f58a1e-18bc-4554-8aad-88881a290a4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/div/div/div/div/div[2]/form/div/textarea</value>
      <webElementGuid>62cfdab1-b864-4575-b836-b3016b2be039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>341d8dd1-4436-4f45-b7a2-7a2b0f8f164c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = concat(&quot;What&quot; , &quot;'&quot; , &quot;s on your mind?&quot;)]</value>
      <webElementGuid>c2173236-cecf-48ed-8250-3eaaa1d44b59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
